### ISSUE TITLE
Autocompletar en "Egreso" de acuerdo al que inicio sesión "cajero"

### ISSUE THREAD

**Issue by NAVIXXX** [EdixCarlos/admin-pagos#15]
Cuando el cajero registra un pago sale el nombre de los otros cajeros, lo cual debería autocompletarse de acuerdo al login del cajero

![Image](https://github.com/EdixCarlos/admin-pagos/assets/51418782/bb8367d4-c76d-4ed6-a5c5-5a0d94e4cf1b)

**Comment by EdixCarlos** [comment]
hecho

**Comment by NAVIXXX** [comment]
"PAGOS"

![Image](https://github.com/EdixCarlos/admin-pagos/assets/51418782/5f3f2699-f399-4f52-8afe-fe790f96eb84)

"egresos"


![Image](https://github.com/EdixCarlos/admin-pagos/assets/51418782/aa25ab46-b2e9-4732-a048-46698f7533d6)

"MATRICULA"


![Image](https://github.com/EdixCarlos/admin-pagos/assets/51418782/8f7a2ebe-0331-462d-ab08-69b37f586217)
