### ISSUE TITLE
Cambiar nombre por fecha inicio

### ISSUE THREAD

**Issue by NAVIXXX** [EdixCarlos/admin-pagos#50]
![Image](https://github.com/EdixCarlos/admin-pagos/assets/51418782/7c6be4fc-ad71-4b06-baa8-70771da2568e)

**Comment by EdixCarlos** [comment]
?

![Image](https://github.com/EdixCarlos/admin-pagos/assets/74202934/db8634c5-a202-436c-b720-4330e26a1c15)
