### ISSUE TITLE
Modificar Tipo de dato al Ingresar Fecha, un formato entendible para q no muestre mensaje error

### ISSUE THREAD

**Issue by NAVIXXX** [EdixCarlos/admin-pagos#6]
![Image](https://github.com/EdixCarlos/admin-pagos/assets/51418782/abd6d443-d3cf-4c00-89ad-04d40e1ae04e)

**Comment by EdixCarlos** [comment]
AGREGAR AYUDA PARA INGRESAR LA FECHA

**Comment by EdixCarlos** [comment]
![Image](https://github.com/EdixCarlos/admin-pagos/assets/74202934/3395257f-0323-4872-8ed9-b4e0266627f7)

ya esta
